version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every 3 months.
      interval: "quarterly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "quarterly"  # We manually lock dependencies in the pixi.lock file so we do not need so frequent updates
