# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ec8da94
_src_path: gh:scipp/copier_template
description: A daemon that creates a raw dataset using scicat interface whenever a
    new file is written by a file-writer.
max_python: '3.12'
min_python: '3.9'
namespace_package: ''
nightly_deps: ''
orgname: ScicatProject
prettyname: Scicat Filewriter Ingest
projectname: scicat-filewriter-ingest
related_projects: streaming-data-types
year: 2024
