# 
# Docker file to create the image to run SciCat Ingestor testing
#
# use miniconda container
FROM continuumio/miniconda3 as conda

# create app folder
RUN mkdir /app
# copy our application
COPY test/scicat_ingestor_tests.py /app/scicat_ingestor_tests.py
COPY conda_env_sci.yml /app/.
# copy config file with version
RUN mkdir /app/config
COPY CI/config.CI.json /app/config/config.json

# create the conda environment
RUN conda env create -f /app/conda_env_sci.yml -n sci

# now downloads the NLTK stopwords
WORKDIR /app

CMD [ \
  "conda", "run", "-n", "sci", "python", "scicat_ingestor_tests.py", "--config-file", "/app/config/config.json", "--verbose", "--debug", "DEBUG" \
]

