site_name: Scicat Ingestor
site_url: 'https://scicatproject.github.io/scicat-ingestor/'
theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tooltips
    - content.code.copy
  palette:
    primary: indigo
    accent: light blue
plugins:
  - search
  - mermaid2
extra:
  generator: false
  version:
    provider: mike
    default: latest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Configuration: user-guide/configuration.md
  - Developer Guide:
      - Getting Started: developer-guide/getting-started.md
      - Documentation: developer-guide/documentation.md
      - ADRs: developer-guide/adrs.md  # There are not many ADRs so they are in one markdown file.
      - Configuration: developer-guide/configuration.md
