name: CI

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.65.0
          frozen: true
          cache: true
          environments: lint
      - run: pixi run lint
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: Apply automatic formatting

  tests:
    name: Tests
    needs: formatting
    strategy:
      matrix:
        os: ['ubuntu-24.04']
    uses: ./.github/workflows/test.yml
    with:
      os-variant: ${{ matrix.os }}

  intergration-tests:
    name: Integration Tests
    needs: [tests, formatting]
    uses: ./.github/workflows/integration.yml
