name: Deploy Documentation for Develop version
# When a push event occurs on the main branch, and the changes are in the documentation folder, the workflow is triggered
on:
  pull_request:  # Remove it once it works
  push:
    branches:
      - main
    paths:
      - 'documentation/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: $(< .github/workflows/python-version-ci)
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements/docs.txt
      - name: Build and Deploy
        working-directory: ./documentation
        run: |
          git fetch origin
          mike deploy --update-alias --push develop
