name: Deploy Documentation for Release version
on:
  release:
    types: [published]
  workflow_dispatch:  # Manually Deploy Documentation

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.65.0
          frozen: true
          cache: true
          environments: docs
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build and Deploy at Release
        working-directory: ./documentation
        run: |
          VERSION=$(git describe --tags --abbrev=0)  # It will use the latest tag as the version
          echo "Deploying $VERSION"
          git fetch origin
          pixi run -e docs mike deploy --update-alias --push $VERSION latest
          pixi run -e docs mike set-default latest --push
